- name: good first issue
  color: 0e8a16
- name: help wanted
  color: 1d76db
- name: documentation
  color: 006b75
- name: bug
  color: d73a4a
- name: enhancement
  color: a2eeef
- name: security
  color: cfd3d7
 - name: hacktoberfest-accepted
   color: 5319e7
 - name: hacktoberfest
   color: ff7f50
